# Generated by Django 4.0.1 on 2022-01-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(to='pokemon.Type'),
        ),
        migrations.DeleteModel(
            name='PokemonType',
        ),
    ]
