# Generated by Django 4.0.1 on 2022-01-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_pokemon_types_delete_pokemontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(blank=True, to='pokemon.Type'),
        ),
    ]
